### ISSUE TITLE
DataValidation on DTOs

### ISSUE THREAD

**Issue by baltermia** [Humteria/humteria-backend#2]

**Comment by mfhum** [comment]
@baltermia in basic:
The [Required] attribute is part of the Data Annotations validation framework in .NET. It can be used to indicate that a property must have a non-null value when being validated, which is useful for ensuring that the property always has a value.

IMO: should still be used, as it's little to no code, and makes it better foreseeable

**Comment by mfhum** [comment]
This shouldn't be done without, as it's de defining part of requirements when receiving and sending requests. Therefore DTOs need DataAnnotations and Models dont

**Comment by baltermia** [comment]
Use `Validator.TryValidateObject()` to validate objects received by controllers. Also, replace any `DataType.Email` Attributes with `DataType.EmailAddress` since [only the latter actually performs a validation check](https://stackoverflow.com/a/59754883/13574233).
If the Validation fails, return a `BadRequest`.

**Comment by baltermia** [comment]
Might even want to use [FluentValidation](https://code-maze.com/fluentvalidation-in-aspnet/). Btw @mfhum codemaze has great documentation for ASP.NET Web-APIs.

**Comment by mfhum** [comment]
> Use `Validator.TryValidateObject()` to validate objects received by controllers. Also, replace any `DataType.Email` Attributes with `DataType.EmailAddress` since [only the latter actually performs a validation check](https://stackoverflow.com/a/59754883/13574233). If the Validation fails, return a `BadRequest`.

would definetly use that validation, maybe makes sense to also go for the "fluent validation"
What's your opintion? I think simple validation should be enough, as .net already does a lot of validation especially based on security

**Comment by mfhum** [comment]
Reopened and renamed for branch

**Comment by mfhum** [comment]
@baltermia will implement basic validation as stated, first maybe we add something like fluentvalidation in future, dont see it atm

**Comment by baltermia** [comment]
@mfhum yes I'd stick to the inbuilt validation and maybe use fluentvalidation some time later
